framework:
    secret: '%env(APP_SECRET)%'

    # Session configuration
     # Session configuration
    session:
        handler_id: 'session.handler.native_file'
        # Ensure other necessary settings for sessions
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_secure: auto
        cookie_httponly: true
        cookie_samesite: 'lax'
        cookie_lifetime: 3600 # 1 hour for example
        enabled: true
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
