framework:
    secret: '%env(APP_SECRET)%'

    router:
        utf8: true
        default_uri: '%env(APP_URL)%'  # ➔ AJOUT obligatoire pour les liens d'email corrects

    session:
        handler_id: 'session.handler.native_file'
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_secure: auto
        cookie_httponly: true
        cookie_samesite: 'lax'
        cookie_lifetime: 3600
        enabled: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
