security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: auto

    role_hierarchy:
        ROLE_ADMIN: [ROLE_ORGANISATEUR, ROLE_PARTICIPANT]

    providers:
        user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: user_provider
            entry_point: App\Security\AppAuthenticator
            custom_authenticator: App\Security\AppAuthenticator
            logout:
                path: /logout
                target: app_home
                csrf_parameter: '_csrf_token'
                csrf_token_id: 'logout'
                invalidate_session: true

    access_control:
        - { path: ^/organizer/invitations/respond, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/organizer, roles: ROLE_ORGANISATEUR }
        - { path: ^/organisateur, roles: ROLE_ORGANISATEUR }
        - { path: ^/participant, roles: ROLE_PARTICIPANT }
        - { path: ^/dashboard, roles: ROLE_PARTICIPANT }
        - { path: ^/mes-evenements, roles: ROLE_PARTICIPANT }
        - { path: ^/event/\d+/presence, roles: ROLE_PARTICIPANT }
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/reset-password, roles: PUBLIC_ACCESS }
        - { path: ^/invitation, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
