security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: auto

    providers:
        user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            pattern: ^/
            lazy: true
            stateless: false
            custom_authenticator: App\Security\AppAuthenticator
            logout:
                path: app_logout
            access_denied_handler: App\Security\AccessDeniedHandler
            
        login:
            pattern: ^/login
            security: false # The login page is public
            access_denied_handler: App\Security\AccessDeniedHandler

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/participant, roles: ROLE_PARTICIPANT }
        - { path: ^/organisateur, roles: ROLE_ORGANISATEUR }
