security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: auto

    providers:
        user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            lazy: true
            provider: user_provider
            custom_authenticator: App\Security\AppAuthenticator
            logout:
                path: /logout        # ← on met un chemin simple

        #     access_denied_handler: App\Security\AccessDeniedHandler

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/participant, roles: ROLE_PARTICIPANT }
        - { path: ^/organisateur, roles: ROLE_ORGANISATEUR }
