controllers:
    resource: ../src/Controller/
    type: attribute
event_create:
    path: /event/create
    controller: App\Controller\EventController::create
invitation_send:
    path: /inviter
    controller: App\Controller\InvitationController::sendInvitation
app_send_invitation:
    path: /invitation/send
    controller: App\Controller\InvitationController::sendInvitation
google_add_event:
  path: /google/add-event
  controller: App\Controller\GoogleController::addEvent
google_calendar_callback:
    path: /calendar/google-callback
    controller: App\Controller\CalendarController::googleCallback
    methods: GET
invitation_index:
    path: /organizer/invitations
    controller: App\Controller\InvitationController::index

invitation_new:
    path: /organizer/invitations/new
    controller: App\Controller\InvitationController::new

invitation_respond:
    path: /invitation/respond/{token}/{response}
    controller: App\Controller\InvitationController::respond
    requirements:
        response: accepted|declined