controllers:
    resource: ../src/Controller/
    type: attribute
event_create:
    path: /event/create
    controller: App\Controller\EventController::create
invitation_send:
    path: /inviter
    controller: App\Controller\InvitationController::sendInvitation
app_send_invitation:
    path: /invitation/send
    controller: App\Controller\InvitationController::sendInvitation
google_add_event:
  path: /google/add-event
  controller: App\Controller\GoogleController::addEvent
