parameters:
  photos_directory: '%kernel.project_dir%/public/uploads/photos'
  google_token_expiration: '%env(int:GOOGLE_TOKEN_EXPIRATION)%'
  app.mailer_from: 'no-reply@votresite.com'
  google_token_file: '%kernel.project_dir%/var/google_token.json'
  app.mail_from: 'no-reply@maplateforme.com'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Security\AppAuthenticator:
    arguments:
      $userRepository: '@App\Repository\UserRepository'

  App\Controller\UserController:
    tags: ['controller.service_arguments']

  App\Service\EventNotificationService:
    arguments:
      $mailer: '@mailer.mailer'
      $userRepository: '@App\Repository\UserRepository'

  App\Service\ReminderService: ~

  App\Service\GoogleCalendarService:
   arguments:
        $googleClientId: '%env(GOOGLE_CLIENT_ID)%'
        $googleClientSecret: '%env(GOOGLE_CLIENT_SECRET)%'
        $googleRedirectUri: '%env(GOOGLE_REDIRECT_URI)%'
        $projectDir: '%kernel.project_dir%'